ldaps_server                   = "directory.element.local"
ldaps_userdn                   = "cn=users,dc=element,dc=local"
ldaps_groupdn                  = "cn=groups,dc=element,dc=local"
ldaps_ca_file                  = "ELN_CA.pem"
code_sign_user_cn_valid_domain = "element.local"
